name: Report an issue with Siyuan Bullet Threading plugin
description: Report an issue with Siyuan Bullet Threading plugin.
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - anarion80
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting bugs only!

        If you have a feature or enhancement request, please use the feature request issue type.

        [feature request]: https://github.com/anarion80/siyuan-bullet-threading/issues/new/choose

  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: >-
        Describe the issue you are experiencing here, to communicate to the
        maintainers. Tell us what you were trying to do and what happened.

        Provide a clear and concise description of what the problem is.
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: dropdown
    id: environment_backend
    validations:
      required: true
    attributes:
      label: What is the backend running environment that has the issue?
      options:
        - windows
        - linux
        - darwin
        - docker
        - ios
        - android
  - type: dropdown
    id: environment_frontend
    validations:
      required: true
    attributes:
      label: What is the frontend running environment that has the issue?
      options:
        - desktop
        - mobile
        - browser-desktop
        - browser-mobile
        - desktop-window
  - type: input
    id: plugin_version
    validations:
      required: true
    attributes:
      label: What version of Siyuan Bullet Threading plugin has the issue?
  - type: input
    id: siyuan_version
    validations:
      required: true
    attributes:
      label: What version of Siyuan has the issue?
      description: >
        Can be found in: `SiYuan` ⇒ `Settings` ⇒ `About` ⇒ `Current version`.
  - type: input
    attributes:
      label: What was the last working version of Siyuan Bullet Threading plugin?
      description: >
        If known, otherwise leave blank.
  - type: markdown
    attributes:
      value: |
        # Details
  - type: textarea
    attributes:
      label: Anything in the logs that might be useful for us?
      description: For example, error message, or stack traces.
      render: text
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.
